#
# Module manifest for module 'IntuneManagement'
#
# Generated by: Mikael Karlsson
#
# Generated on: 21/02/2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'IntuneManagement.psm1'
    
    # Version number of this module.
    ModuleVersion = '4.0.0'
    
    # Supported PSEditions
    # CompatiblePSEditions = @()
    
    # ID used to uniquely identify this module
    GUID = '3c4b3f21-256d-4be0-b106-abcd49ad6423'
    
    # Author of this module
    Author = 'Mikael Karlsson'
    
    # Company or vendor of this module
    # CompanyName = ''
    
    # Copyright statement for this module
    Copyright = '(c) 2019-2026 Mikael Karlsson. Software released under MIT License.'
    
    # Description of the functionality provided by this module
    Description = 'Management of Intune and Azure via Cloud APIs like Microsoft Graph API'
    
    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @()
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    # Connect-EntraEnvironment used to be here as a public API for interactive
    # sign-in. That role now belongs to `Connect-IntuneManagement -Interactive`,
    # which the auth-provider abstraction routes to the right backend
    # (MSAL browser/WAM, OAuth device code, MgGraph interactive). The function
    # is still callable INSIDE the module (UI Login buttons, MSAL provider
    # Refresh/silent-resume, tenant switcher) via ordinary function lookup
    # since it's dot-sourced by the loader — removing it from
    # FunctionsToExport only hides it from consumers of the module.
    FunctionsToExport = @("Show-MainWindow","Connect-IntuneManagement","Invoke-MSGraphAPI","Get-GraphPolicies","Get-GraphPolicyFromFile","Import-GraphPolicy","Export-GraphPolicy","Copy-GraphPolicy","Remove-GraphPolicy","Compare-GraphPolicy","Start-GraphBulkExport","Start-GraphBulkImport","Start-GraphBulkDelete","Start-GraphBulkCopy","Set-GraphBulkAssignments","Set-GraphBulkScopeTags","Save-GraphBulkExportSettings","Get-GraphDocumentation","Start-GraphBulkDocumentation","Get-DocumentationOutput","Get-AuthToken","Get-GraphEffectivePermissions","Get-Setting","Set-Setting","Remove-Setting","Get-SettingDefinition","Use-SettingsStore","Get-SettingsStore","Export-SettingsStore","Import-SettingsStore","Get-AccessibleTenant")
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    # CmdletsToExport = @()
    
    # Variables to export from this module
    # VariablesToExport = ""
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()
    
    # DSC resources to export from this module
    # DscResourcesToExport = @()
    
    # List of all modules packaged with this module. Entries must be module
    # NAMES or ModuleSpecification hashtables - listing this module own .psm1
    # makes Test-ModuleManifest fail with an invalid-entry error.
    # ModuleList = @()
    
    # List of all files packaged with this module
    # FileList = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @("Intune","EndpointManager","IntuneManagement","Microsoft Graph","PowerShell","WPF", "Cloud API")
    
            # A URL to the license for this module.
            # blob/v4, not the bare path: GitHub answers 404 to /LICENSE without a
            # branch, and redirects blob URLs when a branch is renamed.
            LicenseUri = 'https://github.com/Micke-K/IntuneManagement/blob/v4/LICENSE'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Micke-K/IntuneManagement'
    
            # A URL to an icon representing this module.
            # IconUri = ''
    
            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Pre-release tag. ModuleVersion cannot carry a suffix, so the beta
            # marker lives here: the module publishes as 4.0.0-beta1. Remove this
            # line for the GA release of 4.0.0.
            Prerelease = 'beta1'

        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = 'IM'

}
